version: "3.9"

name: sonarqube

services:
  
  postgres:
    container_name: ${PGHOST}
    image: postgres:16.0
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    env_file:
      - .env
    expose:
      - ${PGPORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      - SONARQUBE_JDBC_USERNAME=${PGUSER}
      - SONARQUBE_JDBC_PASSWORD=${PGPASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

      

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  
