name: Build and run Vuejs project

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.17.1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        working-directory: ./front
        run: npm install
      - name: Run tests
        working-directory: ./front
        run: npm run build
